---
galaxy_info:
  author: Patrick Heeney
  company: Protobox
  description: "Phalcon Configuration"
  min_ansible_version: 1.4
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - system

dependencies: []